version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      target-branch: 'develop'
      schedule:
          interval: 'monthly'
      ignore:
          - dependency-name: '*'
            update-types:
                - 'version-update:semver-major'
